## The Out of This World Crew
## 12/1/2020
##
## This driver script downloads the data and runs the analysis for our project.
##

# Downloading the data
data/raw/aliens.csv : src/download_data.py 
  python src/download_data.py --location='BC WA' --output_file=data/raw/aliens.csv

# The cleaning script should be rerun if we redownload the data or pull 
src/times_cleaning.R : src/times_cleaning.R data/raw/aliens.csv
  Rscript src/times_cleaning.R --fp_raw="data/raw/aliens.csv" --fp_pro=" data/processed/aliens.csv"

# Rule for our eda figures
ufo_duration_distriubution.png summary_shape.rds : data/processed/aliens.csv src/ufo_eda.RMD
  script src/ufo_eda_BcWa.R --input_data='data/processed/aliens.csv'  --out_dir='results/'

# Run our analysis
KW.rds Dunn.rds pairwise_plt.png : src/analysis.R
  Rscript src/analysis.R --fp_pro='data/processed/aliens.csv' --fp_results="results/"
  
# Final Report
doc/ufo_report.rmd : KW.rds Dunn.rds pairwise_plt.png summary_shape.rds ufo_duration_summary.rds src/ufo_eda.rmd
  Rscript -e "rmarkdown::render('src/ufo_eda.Rmd')  
  
# Cleaning
clean :
  rm -f data/raw/aliens.csv
  rm -f 

